[app:main]
use = egg:backend

# Matikan semua fitur debug di produksi
pyramid.reload_templates = false
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

# Hapus pyramid_debugtoolbar dari sini
pyramid.includes =
    pyramid_default_cors

# Sesuaikan dengan domain frontend Anda nanti
cors.allow_origin = http://localhost:5173
cors.allow_methods = GET,POST,PUT,DELETE,OPTIONS
cors.allow_headers = Authorization,Content-Type
cors.expose_headers = Authorization
cors.allow_credentials = true

sqlalchemy.url = postgresql://neondb_owner:npg_FQA0p2WeaSxc@ep-flat-wildflower-ah9v5vw6-pooler.c-3.us-east-1.aws.neon.tech/job_portal_db?sslmode=require

retry.attempts = 3

[server:main]
use = egg:waitress#main
# Menggunakan 0.0.0.0 agar bisa diakses dari luar
listen = 0.0.0.0:6543

[loggers]
keys = root, backend, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_backend]
level = INFO
handlers =
qualname = backend

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s