"""update job model

Revision ID: f732ee4bf74f
Revises: e3b635aa625c
Create Date: 2025-12-11 11:38:27.234050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f732ee4bf74f'
down_revision = 'e3b635aa625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
